project:
  type: website
  output-dir: docs
website:
  navbar:
    background: "#00035b"
    foreground: light
    search: true
    left:
      - text: "Home"
        href: about.html
      - text: "Projects"
        href: projects.html
    pinned: true
toc: true
number-sections: true
execute:
  freeze: auto
  
format:
  html:
    html-math-method: katex
